# Generated by Django 5.1.6 on 2025-02-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aparelho', models.CharField(max_length=50)),
                ('descricao_problema', models.TextField()),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], default='Aberta', max_length=15)),
                ('tecnico_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
