# Generated by Django 5.1.6 on 2025-02-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='id',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_os',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
