# Generated by Django 5.1.6 on 2025-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_remove_ordemservico_id_ordemservico_numero_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='numero_os',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
